### ISSUE TITLE
Sandbox | 프로젝트에 적용할 Sandbox 선정

### ISSUE THREAD

**Issue by byObin** [GwooTeam/Quilt-Node#1]
### 문제 상황
- 프로젝트 생성, TGrid에 적용할 Sandbox test 후 프로젝트에 적용할 sandbox 선정

### TODO
- [x] Sandbox 종류 조사
- [x] TGrid 예제코드에서 sandbox 원격 실행 test
- [x] 프로젝트 적용 sandbox 선정
