### ISSUE TITLE
🐛 GUI | Electron환경에서 main프로세스와 renderer프로세스의 통신이 안되는 문제

### ISSUE THREAD

**Issue by LiiNi-coder** [GwooTeam/Quilt-Node#20]
### 문제 상황
- main프로세스(External/GUI/backend/main.ts) 와 renderer프로세스(External/GUI/frontend/)간 IPC가 안되는 문제
- feat/GUI_electron의 커밋 aa7ebae 에서 문제 관찰 가능
- electron창은 나오지만 함수버튼이 동적으로 생성이 안됨.
- electron창의 개발자도구를 보니 script src의 경로문제로 판별됨.

### TODO
- [x] electron 환경의 HTML상에서 script불러올 때 현재경로 파악하기
- [x] 상대경로가 들키는 문제를 해결하기 위한 방법인 webpack 공부 및 적용
- [x] electron 환경의 ts파일 상에서 외부파일 불러올 때 현재경로 파악하기
