### ISSUE TITLE
♿ Sandbox Runner | 클라이언트 구동엔진인 electron 환경에서 Sandbox Runner모듈 연동 시도(like MSA)

### ISSUE THREAD

**Issue by LiiNi-coder** [GwooTeam/Quilt-Node#34]
### 문제 상황
- 클라이언트 구동엔진인 electron환경에서 `Sandbox Runner`모듈을 실행해야함.
-  `Sandbox Runner`는 순전히 여러개의 Python파일로 이뤄져있어 JS기반인 electron환경에서 별도 프로세스상에서 실행이 되어야함
- 하나의 PC에서 MSA시도는 처음이라 다음과 같은 사항들이 이번 실험에서 결정되어야함
- 1. electron상에서 `Sandbox Runner`프로세스의 생명주기 정하기(언제 run? 언제 kill?)
- 2. `Sandbox Runner`가 실행되는 이벤트 정하기(이벤트 트리거 조건은 나중에 정할것임)
- 3. `Sandbox Runner`가 실행되고있는 도중에, `Sandbox Runner`가 실행되는 이벤트가 실행되었을때 처리 방식 정하기

### TODO
- [x] electron 상에서 `Sandbox Runner` 실행하기
- [ ] electron상에서 `Sandbox Runner`프로세스의 생명주기 정하기(언제 run? 언제 kill?)
- [ ] `Sandbox Runner`가 실행되는 이벤트 정하기(이벤트 트리거 조건은 나중에 정할것임)
- [x] `Sandbox Runner`가 실행되고있는 도중에, `Sandbox Runner`가 실행되는 이벤트가 실행되었을때 처리 방식 정하기
