### ISSUE TITLE
도커 이미지 빌드 자동화 구축

### ISSUE THREAD

**Issue by hdXian** [GwooTeam/Quilt-Node#8]
### 문제 상황
- dockerfile에 변경사항이 발생할 경우 이를 반영하여 도커 이미지를 자동으로 빌드하는 환경을 구축

### TODO
- [x] dockerhub 계정 생성
- [x] .github/workflows/build-docker-images.yml 파일 작성
- [x] build-docker-images.yml 파일 수정
